---
title: "Pre-experimental stimulus familiarity modulates the effects of item repetition on source memory"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: cosmo 
    highlight: tango
subtitle: Data & R scripts for analyses
mainfont: Noto Sans CJK KR
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
# install.packages("devtools")
devtools::install_github("ropenscilabs/icon")
```

<br><br>

## Authors

* Hongmi Lee (Johns Hopkins University)
* Kyungmi Kim (Wesleyan University)
* Do-Joon Yi (Yonsei University) 

<br><br>

## Abstract

Previous studies have reported contradictory findings regarding the effects of item repetition on the subsequent encoding of contextual details associated with items (i.e., source memory). Whereas some studies reported repetition-induced enhancement in source memory, other studies observed repetition-induced impairment. To resolve these conflicting results, we examined the modulatory role of pre-experimental stimulus familiarity in the relationship between item repetition and new source memory formation by orthogonally manipulating pre-experimental stimulus familiarity and intra-experimental item repetition. In a series of experiments consisting of three phases (item repetition, item-source association, and source memory test), we found that item repetition impaired source memory for pre-experimentally familiar items (famous faces or words), whereas the same manipulation improved source memory for pre-experimentally novel items (non-famous faces or pseudowords). Crucially, item repetition impaired, rather than improved, source memory for pre-experimentally novel items when these items had been pre-exposed to participants prior to the three-phase procedure. Collectively, these findings provide strong evidence that pre-experimental stimulus familiarity determines the relative costs and benefits of experimental item repetition on the encoding of new item-source associations. By demonstrating the interaction between different types of stimulus familiarity, the present findings advance our understanding of how prior experience affects the formation of new episodic memories. 

<br><br>

## Acknowledgement

This research was supported by the National Research Foundation of Korea under Grant NRF-2017R1D1A1B03028539.

***
[[View on Github `r icon::fa("github", size = 3)`](https://github.com/cogneuro/FamSM)]{style="float:right"}